version: '3.3'

services:
  web:
    build: .
    command: gunicorn website_status.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/website_status
      - static_volume:/website_status/staticfiles
      - media_volume:/website_status/media
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - DOCKER_TLS_VERIFY=0
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
     image: postgres:12
     restart: always
     environment:
       POSTGRES_DB: your_db_name
       POSTGRES_USER: your_db_user
       POSTGRES_PASSWORD: your_db_password
  
 

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/website_status/staticfiles
      - media_volume:/website_status/media
    depends_on:
      - web

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:

